apiVersion: v2
name: monitoring
description: Complete monitoring stack with Grafana, Prometheus, Loki, and Alloy
type: application
version: 1.0.0
appVersion: "1.0.0"

# Dependencies
dependencies:
  # Prometheus + Grafana + Alertmanager
  - name: kube-prometheus-stack
    version: "66.3.1"
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus

  # Loki for log storage
  - name: loki
    version: "6.24.0"
    repository: https://grafana.github.io/helm-charts
    alias: loki

  # Alloy for log collection
  - name: alloy
    version: "0.10.0"
    repository: https://grafana.github.io/helm-charts
    alias: alloy
